### ISSUE TITLE
after adding flyer then press add product flyer screens opens again

### ISSUE THREAD

**Issue by amr021** [ahmedlehamdi/DataEntryApp#2]
after adding flyer then press add product flyer screens opens again

**Comment by ahmedlehamdi** [comment]
Fixed please retest

**Comment by amr021** [comment]
![image](https://user-images.githubusercontent.com/34089272/33523502-43665796-d81a-11e7-92b2-d8c470bb2349.png)

**Comment by ahmedlehamdi** [comment]
This is a data issue. When the user adds the flyer he/she selects the provider of the flyer (ex:Danoub-Othaim-...) then when he/she trying to add the flyer products we retrieve the branches for the selected provider and the test data is only for Othaim provider so please add branches for other providers.

![image](https://user-images.githubusercontent.com/2698698/33529910-027ca546-d888-11e7-83d5-8722604105f4.png)

**Comment by ahmedlehamdi** [comment]
Branches Data issue check the Whatsapp for screens
